name: "test"

on:
  push:
    branches:
      - master
  pull_request:

# Remember to update me!
env:
  vessel_version: "v0.6.5"
  moc_version: "0.8.8"

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm clean-install
      - name: "check prettier"
        run: npm run prettier:check
      - name: "audit"
        run: npm audit
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - name: "install dependencies"
        run: |
          nix-env --install wasmtime --file '<nixpkgs>'
      - name: "install Motoko binaries"
        run: |
          wget https://github.com/dfinity/motoko/releases/download/${{ env.moc_version }}/motoko-linux64-${{ env.moc_version }}.tar.gz
          mkdir -p /home/runner/bin
          tar -xzf motoko-linux64-${{ env.moc_version }}.tar.gz -C /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH
      - name: "install vessel"
        run: |
          wget --output-document /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/${{ env.vessel_version }}/vessel-linux64
          chmod +x /home/runner/bin/vessel
          vessel install
      - name: "install dfx"
        run: sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      - name: "run tests"
        run: |
          dfx start --background
          npm test
          dfx stop
